--SECUENCIAS DE BD POSTULANTE
CREATE SEQUENCE SEQ_GRADO_ACADEM
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_UBIGEO
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_ESTAD_CIV
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_IDIOMA
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_NIVEL_IDIOMA
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_IDIOMA_POST
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_POSTULANTE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_FORMA_ACADEM
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_CAT_BREVETE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_BREVETE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_DETALLE_FORM
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_TIPO_FORM_ACA
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_AREA
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_CARGO
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_EMPRESA
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_CAPACITACION
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_SALARIO
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_JEFE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_EXPE_LABO
START WITH 1
INCREMENT BY 1;