-- AGREGAR CAMPO ESTADO A LAS TABLAS NORMALIZADAS
ALTER TABLE AREA ADD ESTADO INT DEFAULT 0;
ALTER TABLE BREVETE ADD ESTADO INT DEFAULT 0;
ALTER TABLE CAPACITACION ADD ESTADO INT DEFAULT 0;
ALTER TABLE CARGO ADD ESTADO INT DEFAULT 0;
ALTER TABLE CAT_BREVETE ADD ESTADO INT DEFAULT 0;
ALTER TABLE DETALLE_FORM ADD ESTADO INT DEFAULT 0;
ALTER TABLE EMPRESA ADD ESTADO INT DEFAULT 0;
ALTER TABLE ESTAD_CIV ADD ESTADO INT DEFAULT 0;
ALTER TABLE EXPE_LABO ADD ESTADO INT DEFAULT 0;
ALTER TABLE FORMA_ACADEM ADD ESTADO INT DEFAULT 0;
ALTER TABLE GRADO_ACADEM ADD ESTADO INT DEFAULT 0;
ALTER TABLE IDIOMA ADD ESTADO INT DEFAULT 0;
ALTER TABLE IDIOMA_POST ADD ESTADO INT DEFAULT 0;
ALTER TABLE JEFE ADD ESTADO INT DEFAULT 0;
ALTER TABLE NIVEL_IDIOMA ADD ESTADO INT DEFAULT 0;
ALTER TABLE POSTULANTE ADD ESTADO INT DEFAULT 0;
ALTER TABLE SALARIO ADD ESTADO INT DEFAULT 0;
ALTER TABLE TIPO_FORM_ACA ADD ESTADO INT DEFAULT 0;
ALTER TABLE UBIGEO ADD ESTADO INT DEFAULT 0;

--TABLAS NORMALIZADAS
SELECT * FROM AREA;
SELECT * FROM BREVETE;
SELECT * FROM CAPACITACION;
SELECT * FROM CARGO;
SELECT * FROM CAT_BREVETE;
SELECT * FROM DETALLE_FORM;
SELECT * FROM EMPRESA;
SELECT * FROM ESTAD_CIV;
SELECT * FROM EXPE_LABO;
SELECT * FROM FORMA_ACADEM;
SELECT * FROM GRADO_ACADEM;
SELECT * FROM IDIOMA;
SELECT * FROM IDIOMA_POST;
SELECT * FROM JEFE;
SELECT * FROM NIVEL_IDIOMA;
SELECT * FROM POSTULANTE;
SELECT * FROM SALARIO;
SELECT * FROM TIPO_FORM_ACA;
SELECT * FROM UBIGEO;







