--SCRIPT TRANFERENCIA A TABLAS MESTRAS
INSERT INTO GRADO_ACADEM
SELECT SEQ_GRADO_ACADEM.NEXTVAL,CODIGO_GRA_ACA,GRADO_ACADEM,0 FROM
(
    SELECT T.CODIGO_GRA_ACA,T.GRADO_ACADEM FROM TMP_GRADO_ACADEM  T
    WHERE NOT EXISTS(
    SELECT * FROM GRADO_ACADEM G
    WHERE G.CODIGO_GRA_ACA = T.CODIGO_GRA_ACA AND G.GRADO_ACADEM = T.GRADO_ACADEM
    )
    GROUP BY T.CODIGO_GRA_ACA,T.GRADO_ACADEM
    ORDER BY 1
);
SELECT * FROM GRADO_ACADEM;


INSERT INTO UBIGEO 
SELECT SEQ_UBIGEO.NEXTVAL,CODIGO_UBIGEO,DISTRITO,PROVINCIA,DEPARTAMENTO,0 FROM
(
    SELECT T.CODIGO_UBIGEO,T.DISTRITO,T.PROVINCIA,T.DEPARTAMENTO FROM TMP_UBIGEO T
    WHERE NOT EXISTS(
    SELECT * FROM UBIGEO U
    WHERE U.CODIGO_UBIGEO = T.CODIGO_UBIGEO AND U.DISTRITO = T.DISTRITO AND U.PROVINCIA = T.PROVINCIA AND U.DEPARTAMENTO = T.DEPARTAMENTO
    )
    GROUP BY T.CODIGO_UBIGEO,T.DISTRITO,T.PROVINCIA,T.DEPARTAMENTO
    ORDER BY 1
);
SELECT * FROM UBIGEO;


INSERT INTO ESTAD_CIV 
SELECT SEQ_ESTAD_CIV.NEXTVAL,CODIGO_EST_CIV,ESTADO_CIVIL,0 FROM
(
    SELECT T.CODIGO_EST_CIV,T.ESTADO_CIVIL FROM TMP_ESTAD_CIV T
    WHERE NOT EXISTS(
    SELECT * FROM ESTAD_CIV E
    WHERE E.CODIGO_EST_CIV = T.CODIGO_EST_CIV AND E.ESTADO_CIVIL = T.ESTADO_CIVIL
    )
    GROUP BY T.CODIGO_EST_CIV,T.ESTADO_CIVIL
    ORDER BY 1
);
SELECT * FROM ESTAD_CIV;


INSERT INTO CAT_BREVETE 
SELECT SEQ_CAT_BREVETE.NEXTVAL,CODIGO_CAT_BREV,CATE_BREV,0 FROM
(
    SELECT T.CODIGO_CAT_BREV,T.CATE_BREV FROM TMP_CAT_BREVETE T
    WHERE NOT EXISTS(
    SELECT * FROM CAT_BREVETE  C
    WHERE C.CODIGO_CAT_BREV = T.CODIGO_CAT_BREV AND C.CATE_BREV = T.CATE_BREV
    )
    GROUP BY T.CODIGO_CAT_BREV,T.CATE_BREV
    ORDER BY 1
);
SELECT * FROM CAT_BREVETE;


INSERT INTO NIVEL_IDIOMA
SELECT SEQ_NIVEL_IDIOMA.NEXTVAL,CODIGO_NIV_IDIOMA,NIVEL_IDIOMA,0 FROM
(
    SELECT T.CODIGO_NIV_IDIOMA,T.NIVEL_IDIOMA FROM TMP_NIVEL_IDIOMA T
    WHERE NOT EXISTS(
    SELECT * FROM NIVEL_IDIOMA N
    WHERE N.CODIGO_NIV_IDIOMA = T.CODIGO_NIV_IDIOMA AND N.NIVEL_IDIOMA = T.NIVEL_IDIOMA
    )
    GROUP BY T.CODIGO_NIV_IDIOMA,T.NIVEL_IDIOMA
    ORDER BY 1
);
SELECT * FROM NIVEL_IDIOMA;


INSERT INTO IDIOMA
SELECT SEQ_IDIOMA.NEXTVAL,CODIGO_IDIOMA,IDIOMA,0 FROM
(
    SELECT T.CODIGO_IDIOMA,T.IDIOMA FROM TMP_IDIOMA T
    WHERE NOT EXISTS(
    SELECT * FROM IDIOMA I
    WHERE I.CODIGO_IDIOMA = T.CODIGO_IDIOMA AND I.IDIOMA = T.IDIOMA
    )
    GROUP BY T.CODIGO_IDIOMA,T.IDIOMA
    ORDER BY 1
);
SELECT * FROM IDIOMA;


INSERT INTO JEFE
SELECT SEQ_JEFE.NEXTVAL,CODIGO_JEFE,NOMBRE_JEFE,CARGO_JEFE,0 FROM
(
    SELECT T.CODIGO_JEFE,T.NOMBRE_JEFE,CARGO_JEFE FROM TMP_JEFE T
    WHERE NOT EXISTS(
    SELECT * FROM JEFE J
    WHERE J.CODIGO_JEFE = T.CODIGO_JEFE AND J.NOMBRE_JEFE = T.NOMBRE_JEFE AND J.CARGO_JEFE = T.CARGO_JEFE
    )
    GROUP BY T.CODIGO_JEFE,T.NOMBRE_JEFE,CARGO_JEFE
    ORDER BY 1
);
SELECT * FROM JEFE;


INSERT INTO SALARIO
SELECT SEQ_SALARIO.NEXTVAL,CODIGO_SALARIO,SALARIO,0 FROM
(
    SELECT T.CODIGO_SALARIO,T.SALARIO FROM TMP_SALARIO T
    WHERE NOT EXISTS(
    SELECT * FROM SALARIO S
    WHERE S.CODIGO_SALARIO = T.CODIGO_SALARIO AND S.SALARIO = T.SALARIO
    )
    GROUP BY T.CODIGO_SALARIO,T.SALARIO
    ORDER BY 1
);
SELECT * FROM SALARIO;


INSERT INTO CAPACITACION
SELECT SEQ_CAPACITACION.NEXTVAL,CODIGO_CAPACI,INICIO_MES_AÑO,FIN_MES_AÑO,CURSO_EVENTO,INSTITUCION,HORAS_LECT,0 FROM
(
    SELECT T.CODIGO_CAPACI,T.INICIO_MES_AÑO,T.FIN_MES_AÑO,T.CURSO_EVENTO,T.INSTITUCION,T.HORAS_LECT FROM TMP_CAPACITACION T
    WHERE NOT EXISTS(
    SELECT * FROM CAPACITACION C
    WHERE C.CODIGO_CAPACI = T.CODIGO_CAPACI
        AND C.INICIO_MES_AÑO = T.INICIO_MES_AÑO
        AND C.FIN_MES_AÑO = T.FIN_MES_AÑO
        AND C.CURSO_EVENTO = T.CURSO_EVENTO
        AND C.INSTITUCION = T.INSTITUCION
        AND C.HORAS_LECT = T.HORAS_LECT
    )
    GROUP BY T.CODIGO_CAPACI,T.INICIO_MES_AÑO,T.FIN_MES_AÑO,T.CURSO_EVENTO,T.INSTITUCION,T.HORAS_LECT
    ORDER BY 1
);
SELECT * FROM CAPACITACION;


INSERT INTO CARGO
SELECT SEQ_CARGO.NEXTVAL,CODIGO_CARGO,CARGO,0 FROM
(
    SELECT T.CODIGO_CARGO,T.CARGO FROM TMP_CARGO T
    WHERE NOT EXISTS(
    SELECT * FROM CARGO C
    WHERE C.CODIGO_CARGO = T.CODIGO_CARGO AND C.CARGO = T.CARGO
    )
    GROUP BY T.CODIGO_CARGO,T.CARGO
    ORDER BY 1
);
SELECT * FROM CARGO;


INSERT INTO EMPRESA
SELECT SEQ_EMPRESA.NEXTVAL,CODIGO_EMPRESA,NOMBRE_EMPRESA,0 FROM
(
    SELECT T.CODIGO_EMPRESA,T.NOMBRE_EMPRESA FROM TMP_EMPRESA T
    WHERE NOT EXISTS(
    SELECT * FROM EMPRESA E
    WHERE E.CODIGO_EMPRESA = T.CODIGO_EMPRESA AND E.NOMBRE_EMPRESA = T.NOMBRE_EMPRESA
    )
    GROUP BY T.CODIGO_EMPRESA,T.NOMBRE_EMPRESA
    ORDER BY 1
);
SELECT * FROM EMPRESA;


INSERT INTO AREA
SELECT SEQ_AREA.NEXTVAL,CODIGO_AREA,AREA,0 FROM
(
    SELECT T.CODIGO_AREA,T.AREA FROM TMP_AREA T
    WHERE NOT EXISTS(
    SELECT * FROM AREA A
    WHERE A.CODIGO_AREA = T.CODIGO_AREA AND A.AREA = T.AREA
    )
    GROUP BY T.CODIGO_AREA,T.AREA
    ORDER BY 1
);
SELECT * FROM AREA;


INSERT INTO TIPO_FORM_ACA
SELECT SEQ_TIPO_FORM_ACA.NEXTVAL,CODIGO_TIPO_FA,TIPO_FORM,0 FROM
(
    SELECT T.CODIGO_TIPO_FA,T.TIPO_FORM FROM TMP_TIPO_FORM_ACA T
    WHERE NOT EXISTS(
    SELECT * FROM TIPO_FORM_ACA F
    WHERE F.CODIGO_TIPO_FA = T.CODIGO_TIPO_FA AND F.TIPO_FORM = T.TIPO_FORM
    )
    GROUP BY T.CODIGO_TIPO_FA,T.TIPO_FORM
    ORDER BY 1
);
SELECT * FROM TIPO_FORM_ACA;







