--TRANSFERENCIA A TABLAS DETALLE

INSERT INTO BREVETE
SELECT SEQ_BREVETE.NEXTVAL,CODIGO_BREVETE,BREVETE,CODIGO_CAT_BREV,ID_CAT_BREV,0 FROM
(
    SELECT T.CODIGO_BREVETE,T.BREVETE,T.CODIGO_CAT_BREV,C.ID_CAT_BREV FROM TMP_BREVETE T
    INNER JOIN CAT_BREVETE C ON (C.CODIGO_CAT_BREV = T.CODIGO_CAT_BREV)
    WHERE NOT EXISTS(
    SELECT * FROM BREVETE B
        WHERE B.CODIGO_BREVETE = T.CODIGO_BREVETE 
        AND B.BREVETE = T.BREVETE 
        AND C.CODIGO_CAT_BREV = T.CODIGO_CAT_BREV
    )
    GROUP BY T.CODIGO_BREVETE,T.BREVETE,T.CODIGO_CAT_BREV,C.ID_CAT_BREV
    ORDER BY 1
);
SELECT * FROM BREVETE;


INSERT INTO FORMA_ACADEM
SELECT SEQ_FORMA_ACADEM.NEXTVAL,CODIGO_FOR_ACA,NOM_INST,PRO_ESP,FECHA_INICIO,FECHA_FIN,CODIGO_GRA_ACA,ID_GRA_ACA,0 FROM
(
    SELECT T.CODIGO_FOR_ACA,T.NOM_INST,T.PRO_ESP,T.FECHA_INICIO,T.FECHA_FIN,T.CODIGO_GRA_ACA,G.ID_GRA_ACA FROM TMP_FORMA_ACADEM T
    INNER JOIN GRADO_ACADEM G ON (G.CODIGO_GRA_ACA = T.CODIGO_GRA_ACA)
    WHERE NOT EXISTS(
    SELECT * FROM FORMA_ACADEM F
        WHERE F.CODIGO_FOR_ACA = T.CODIGO_FOR_ACA 
        AND F.NOM_INST = T.NOM_INST 
        AND F.PRO_ESP = T.PRO_ESP
        AND F.FECHA_INICIO = T.FECHA_INICIO
        AND F.FECHA_FIN = T.FECHA_FIN
        AND G.CODIGO_GRA_ACA = T.CODIGO_GRA_ACA
    )
    GROUP BY T.CODIGO_FOR_ACA,T.NOM_INST,T.PRO_ESP,T.FECHA_INICIO,T.FECHA_FIN,T.CODIGO_GRA_ACA,G.ID_GRA_ACA
    ORDER BY 1
);
SELECT * FROM FORMA_ACADEM;


INSERT INTO POSTULANTE
SELECT SEQ_POSTULANTE.NEXTVAL,CODIGO_POSTULANTE,APE_PATERNO,APE_MATERNO,NOMBRES,EDAD,FEC_NAC,SEXO,DNI,RUC,DIRECCION,LT_MZ,TEL_FIJO,TEL_CELULAR,CORREO,LUGAR_NAC,CODIGO_UBIGEO,CODIGO_EST_CIV,CODIGO_BREVETE,ID_EST_CIV,ID_BREVETE,ID_UBIGEO,0 FROM
(
    SELECT T.CODIGO_POSTULANTE,T.APE_PATERNO,T.APE_MATERNO,T.NOMBRES,T.EDAD,T.FEC_NAC,T.SEXO,T.DNI,T.RUC,T.DIRECCION,T.LT_MZ,T.TEL_FIJO,T.TEL_CELULAR,T.CORREO,T.LUGAR_NAC,T.CODIGO_UBIGEO,T.CODIGO_EST_CIV,T.CODIGO_BREVETE,C.ID_EST_CIV,B.ID_BREVETE,U.ID_UBIGEO FROM TMP_POSTULANTE T
    INNER JOIN UBIGEO U ON (U.CODIGO_UBIGEO = T.CODIGO_UBIGEO)
    INNER JOIN ESTAD_CIV C ON (C.CODIGO_EST_CIV = T.CODIGO_EST_CIV)
    INNER JOIN BREVETE B ON (B.CODIGO_BREVETE = T.CODIGO_BREVETE)
    WHERE NOT EXISTS(
    SELECT * FROM POSTULANTE P
        WHERE P.CODIGO_POSTULANTE = T.CODIGO_POSTULANTE 
        AND P.APE_PATERNO = T.APE_PATERNO 
        AND P.APE_MATERNO = T.APE_MATERNO
        AND P.NOMBRES = T.NOMBRES
        AND P.EDAD = T.EDAD
        AND P.FEC_NAC = T.FEC_NAC
        AND P.SEXO = T.SEXO
        AND P.DNI = T.DNI
        AND P.RUC = T.RUC
        AND P.DIRECCION = T.DIRECCION
        AND P.TEL_FIJO = T.TEL_FIJO
        AND P.TEL_CELULAR = T.TEL_CELULAR
        AND P.CORREO = T.CORREO
        AND P.LUGAR_NAC = T.LUGAR_NAC
        AND U.CODIGO_UBIGEO = T.CODIGO_UBIGEO
        AND C.CODIGO_EST_CIV = T.CODIGO_EST_CIV
        AND P.CODIGO_BREVETE = T.CODIGO_BREVETE
    )
    GROUP BY T.CODIGO_POSTULANTE,T.APE_PATERNO,T.APE_MATERNO,T.NOMBRES,T.EDAD,T.FEC_NAC,T.SEXO,T.DNI,T.RUC,T.DIRECCION,T.LT_MZ,T.TEL_FIJO,T.TEL_CELULAR,T.CORREO,T.LUGAR_NAC,T.CODIGO_UBIGEO,T.CODIGO_EST_CIV,T.CODIGO_BREVETE,C.ID_EST_CIV,B.ID_BREVETE,U.ID_UBIGEO
    ORDER BY 1
);
SELECT * FROM POSTULANTE;


INSERT INTO IDIOMA_POST
SELECT SEQ_IDIOMA_POST.NEXTVAL,CODIGO_IDIPOS,CODIGO_POSTULANTE,CODIGO_IDIOMA,CODIGO_NIV_IDIOMA,ID_IDIOMA,ID_NIV_IDIOMA,ID_POSTULANTE,0 FROM
(
    SELECT T.CODIGO_IDIPOS,T.CODIGO_POSTULANTE,T.CODIGO_IDIOMA,T.CODIGO_NIV_IDIOMA,I.ID_IDIOMA,N.ID_NIV_IDIOMA,P.ID_POSTULANTE FROM TMP_IDIOMA_POST T
    INNER JOIN POSTULANTE P ON (P.CODIGO_POSTULANTE = T.CODIGO_POSTULANTE)
    INNER JOIN IDIOMA I ON (I.CODIGO_IDIOMA = T.CODIGO_IDIOMA)
    INNER JOIN NIVEL_IDIOMA N ON (N.CODIGO_NIV_IDIOMA = T.CODIGO_NIV_IDIOMA)
    WHERE NOT EXISTS(
    SELECT * FROM IDIOMA_POST IP
        WHERE IP.CODIGO_IDIPOS = T.CODIGO_IDIPOS 
        AND P.CODIGO_POSTULANTE = T.CODIGO_POSTULANTE 
        AND I.CODIGO_IDIOMA = T.CODIGO_IDIOMA
        AND N.CODIGO_NIV_IDIOMA = T.CODIGO_NIV_IDIOMA
    )
    GROUP BY T.CODIGO_IDIPOS,T.CODIGO_POSTULANTE,T.CODIGO_IDIOMA,T.CODIGO_NIV_IDIOMA,I.ID_IDIOMA,N.ID_NIV_IDIOMA,P.ID_POSTULANTE
    ORDER BY 1
);
SELECT * FROM IDIOMA_POST;


INSERT INTO DETALLE_FORM
SELECT SEQ_DETALLE_FORM.NEXTVAL,CODIGO_DETALLE_FORM,CODIGO_FORM_ACA,CODIGO_TIPO_FA,CODIGO_POSTULANTE,ID_FOR_ACA,ID_TIPO_FA,ID_POSTULANTE,0 FROM
(
    SELECT T.CODIGO_DETALLE_FORM,T.CODIGO_FORM_ACA,T.CODIGO_TIPO_FA,T.CODIGO_POSTULANTE,F.ID_FOR_ACA,TI.ID_TIPO_FA,P.ID_POSTULANTE FROM TMP_DETALLE_FORM T
    INNER JOIN FORMA_ACADEM F ON (F.CODIGO_FOR_ACA = T.CODIGO_FORM_ACA)
    INNER JOIN TIPO_FORM_ACA TI ON (TI.CODIGO_TIPO_FA = T.CODIGO_TIPO_FA)
    INNER JOIN POSTULANTE P ON (P.CODIGO_POSTULANTE = T.CODIGO_POSTULANTE)
    WHERE NOT EXISTS(
    SELECT * FROM DETALLE_FORM D
        WHERE D.CODIGO_DETALLE_FORM = T.CODIGO_DETALLE_FORM 
        AND F.CODIGO_FOR_ACA = T.CODIGO_FORM_ACA 
        AND TI.CODIGO_TIPO_FA = T.CODIGO_TIPO_FA
        AND P.CODIGO_POSTULANTE = T.CODIGO_POSTULANTE
    )
    GROUP BY T.CODIGO_DETALLE_FORM,T.CODIGO_FORM_ACA,T.CODIGO_TIPO_FA,T.CODIGO_POSTULANTE,F.ID_FOR_ACA,TI.ID_TIPO_FA,P.ID_POSTULANTE
    ORDER BY 1
);
SELECT * FROM DETALLE_FORM;


INSERT INTO EXPE_LABO
SELECT SEQ_EXPE_LABO.NEXTVAL,CODIGO_EXP_LAB,FUNC_PRINCIP,MOD_CONT,MOT_RETIRO,TIEMPO_SERV,FECHA_INICIO,FECHA_FIN,TEL_OFICINA,CODIGO_JEFE,CODIGO_CAPACI,CODIGO_EMPRESA,CODIGO_CARGO,CODIGO_AREA,CODIGO_SALARIO,CODIGO_POSTULANTE,ID_JEFE,ID_CAPACI,ID_EMPRESA,ID_CARGO,ID_AREA,ID_SLARIO,ID_POSTULANTE,0 FROM
(
    SELECT T.CODIGO_EXP_LAB,T.FUNC_PRINCIP,T.MOD_CONT,T.MOT_RETIRO,T.TIEMPO_SERV,T.FECHA_INICIO,T.FECHA_FIN,T.TEL_OFICINA,T.CODIGO_JEFE,T.CODIGO_CAPACI,T.CODIGO_EMPRESA,T.CODIGO_CARGO,T.CODIGO_AREA,T.CODIGO_SALARIO,T.CODIGO_POSTULANTE,J.ID_JEFE,C.ID_CAPACI,E.ID_EMPRESA,G.ID_CARGO,A.ID_AREA,S.ID_SLARIO,P.ID_POSTULANTE FROM TMP_EXPE_LABO T
    INNER JOIN JEFE J ON (J.CODIGO_JEFE = T.CODIGO_JEFE)
    INNER JOIN CAPACITACION C ON (C.CODIGO_CAPACI = T.CODIGO_CAPACI)
    INNER JOIN EMPRESA E ON (E.CODIGO_EMPRESA = T.CODIGO_EMPRESA)
    INNER JOIN CARGO G ON (G.CODIGO_CARGO = T.CODIGO_CARGO)
    INNER JOIN AREA A ON (A.CODIGO_AREA = T.CODIGO_AREA)
    INNER JOIN SALARIO S ON (S.CODIGO_SALARIO = T.CODIGO_SALARIO)
    INNER JOIN POSTULANTE P ON (P.CODIGO_POSTULANTE = T.CODIGO_POSTULANTE)
    WHERE NOT EXISTS(
    SELECT * FROM EXPE_LABO EL
        WHERE EL.CODIGO_EXP_LAB = T.CODIGO_EXP_LAB
        AND EL.FUNC_PRINCIP = T.FUNC_PRINCIP 
        AND EL.MOD_CONT = T.MOD_CONT
        AND EL.MOT_RETIRO = T.MOT_RETIRO
        AND EL.TIEMPO_SERV = T.TIEMPO_SERV
        AND EL.FECHA_INICIO = T.FECHA_INICIO
        AND EL.FECHA_FIN = T.FECHA_FIN
        AND EL.TEL_OFICINA = T.TEL_OFICINA
        AND J.CODIGO_JEFE = T.CODIGO_JEFE
        AND C.CODIGO_CAPACI = T.CODIGO_CAPACI
        AND E.CODIGO_EMPRESA = T.CODIGO_EMPRESA
        AND G.CODIGO_CARGO = T.CODIGO_CARGO
        AND A.CODIGO_AREA = T.CODIGO_AREA
        AND S.CODIGO_SALARIO = T.CODIGO_SALARIO
        AND P.CODIGO_POSTULANTE = T.CODIGO_POSTULANTE
    )
    GROUP BY T.CODIGO_EXP_LAB,T.FUNC_PRINCIP,T.MOD_CONT,T.MOT_RETIRO,T.TIEMPO_SERV,T.FECHA_INICIO,T.FECHA_FIN,T.TEL_OFICINA,T.CODIGO_JEFE,T.CODIGO_CAPACI,T.CODIGO_EMPRESA,T.CODIGO_CARGO,T.CODIGO_AREA,T.CODIGO_SALARIO,T.CODIGO_POSTULANTE,J.ID_JEFE,C.ID_CAPACI,E.ID_EMPRESA,G.ID_CARGO,A.ID_AREA,S.ID_SLARIO,P.ID_POSTULANTE
    ORDER BY 1
);
SELECT * FROM EXPE_LABO;









